version: '3'

networks:
  jcard:

services:
  holder:
    depends_on:
      - issuer
    build:
      context: .
      dockerfile: holder/Dockerfile
    container_name: holder
    image: holder:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /dev/urandom:/dev/random
      - holder:/home/app
    entrypoint: "/home/app/holder"
    environment:
      - PRIVATE_KEY=<PRIVATE_KEY>
    networks:
      jcard:
        aliases:
          - holder.local
  issuer:
    build:
      context: .
      dockerfile: issuer/Dockerfile
    container_name: issuer
    image: issuer:latest
    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
      - issuer:/home/app
    entrypoint: "/home/app/issuer"
    environment:
      - PRIVATE_KEY=<PRIVATE_KEY>
    networks:
      jcard:
        aliases:
          - issuer.local
  verifier:
    build:
      context: .
      dockerfile: verifier/Dockerfile
    container_name: verifier
    image: verifier:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /dev/urandom:/dev/random
      - verifier:/home/app
    entrypoint: "/home/app/issuer"
    environment:
      - DOMAIN_NAME=http://localhost:9090
    networks:
      jcard:
        aliases:
          - verifier.local

volumes:
  holder:
  issuer:
  verifier:
