issuer:
  url: ${ISSUER_URL:-http://localhost:8090}
  id: 116GWDn9usS47AyRQHVtLfx9hF9rdsFiyVsH7obPN7
  dataDirectory: ${ISSUER_DATA_DIR:-../data}

circuits:
  path: ${CIRCUITS_PATH:-../static/compiled-circuits/}
  js: ${CIRCUITS_JS:-../static/js/}

web3:
  stateTransition: "0x87B36cE5393D4ea6EEf3eb7b1ca6aAd7ae295D4F"
  url: "https://rpc-mumbai.maticvigil.com/"
  chainID: 80001
  privateKey: ${PRIVATE_KEY}
