issuer:
  url: http://localhost:8090
  id: 119q1hRD7bDXAdESxC9HdxPru2Ejv61JZZ8XK42UwR

circuits:
  path: ../static/compiled-circuits/
  js: ../static/js/

web3:
  stateTransition: "0x36903ff6896444251cED8Da47326De635a3c9d9d"
  url: "https://polygon-testnet.public.blastapi.io"
  chainID: 80001
  privateKey: "<PRIVATE_KEY>"







git ad





















